name: Unzip build

on:
  push:
    paths:
      - 'build.zip'

permissions:
  contents: write   # 🔥 BU ÇOK ÖNEMLİ

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Unzip
        run: |
          unzip build.zip -d temp
          cp -r temp/* .
          rm -rf temp build.zip

      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "unzip build"
          git push
